data1<-read.delim( "T2D.criteria.txt", header=T)
dim(data1)
head(data1,n=3)
data2<-read.delim( "PCAtestdata(1).txt", header=T)
dim(data2)
head(data2,n=3)
data3<-read.delim("T2D case.other.criteria.txt" ,header=T)
dim(data3)
head(data3,n=3)
data4<-merge(data1,data2, by="PATIENT", all.x=TRUE, all.y=TRUE)
dim(data4)
head(data4,n=3)
data5<-merge(data4,data3,by="PATIENT",all.x=TRUE, all.y=TRUE)
write.table(data5,"~/Desktop/pca.case.txt", sep="\t", row.names=FALSE, quote = FALSE)
dim(data5)
head(data5,n=3)
data6<-read.delim( "T2D.ancestral.case.txt" , header=T)
dim(data6)
head(data6,n=3)
sub.PCA.case1<-subset(data6,Ourcase %in% c("East Polynesian"), value=TRUE)
dim (sub.PCA.case1)
head(sub.PCA.case1,n=3)
sub.PCA.case2<-subset(data6, Ourcase %in% c("West Polynesian"),value=TRUE)
dim (sub.PCA.case2)
head(sub.PCA.case2,n=3)
sub.PCA.case3<-subset(data6, Ourcase %in% c("European"),value=TRUE)
dim (sub.PCA.case3)
head(sub.PCA.case3,n=3)
sub.PCA.case4<-subset(data6,Others %in% c("South Asian"),value=TRUE)
dim (sub.PCA.case4)
head(sub.PCA.case4,n=3)
sub.PCA.case5<-subset(data6, Others %in% c("African"),value=TRUE)
dim (sub.PCA.case5)
head(sub.PCA.case5,n=3)
sub.PCA.case6<-subset(data6, Ourcase %in% c("Polynesian"),value=TRUE)
dim (sub.PCA.case6)
head(sub.PCA.case6,n=3)
sub.PCA.case7<-subset(data6, Others %in% c("Unspecified"),value=TRUE)
dim (sub.PCA.case7)
head(sub.PCA.case7,n=3)