data1<-read.delim( "T2D.criteria.txt", header=T)
dim(data1)
data2<-read.delim( "PCAtestdata(1).txt", header=T)
dim(data2)
data3<-read.delim("T2D.other.criteria.txt" ,header=T)
dim(data3)
data4<-merge(data1,data2, by="PATIENT", all.x=TRUE, all.y=TRUE)
data5<-merge(data4,data3,by="PATIENT",all.x=TRUE, all.y=TRUE)
write.table(data5,"~/Desktop/pca.case.txt", sep="\t", row.names=FALSE, quote = FALSE)
data6<-read.delim( "pca.case1.txt" , header=T)
sub.PCA.case1<-subset(data6,Ourcase %in% c("East Polynesian"), value=TRUE)
sub.PCA.case2<-subset(data6, Ourcase %in% c("West Polynesian"),value=TRUE)
sub.PCA.case3<-subset(data6, Ourcase %in% c("European"),value=TRUE)
sub.PCA.case4<-subset(data6,Others %in% c("South Asian"),value=TRUE)
sub.PCA.case5<-subset(data6, Others %in% c("African"),value=TRUE)
sub.PCA.case6<-subset(data6, Ourcase %in% c("Polynesian"),value=TRUE)
sub.PCA.case7<-subset(data6, Others %in% c("Unspecified"),value=TRUE)

